"""empty message

Revision ID: fd4bb8017a64
Revises: 094d7f68329a
Create Date: 2023-10-30 03:26:48.940606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd4bb8017a64'
down_revision = '094d7f68329a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=False))
        batch_op.drop_constraint('product_cantidad_key', type_='unique')
        batch_op.create_unique_constraint(None, ['amount'])
        batch_op.drop_column('precio')
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('precio', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('product_cantidad_key', ['cantidad'])
        batch_op.drop_column('amount')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
